fix AttributeError: 'NoneType' object has no attribute 'group'
The problem was due to VERSION variable getting set to a value which
didn't match the regex in auditwheel [1]. This was happening because
`git describe --always` was returning just the abbreviated git commit
hash. By setting the git clone depth to unlimited, this problem should be avoided.

1. https://github.com/pypa/auditwheel/blob/master/auditwheel/repair.py#L24