arm64 builds would need to wait
Python compilation is broken with:

/usr/xcc/aarch64-unknown-linux-gnueabi/bin/aarch64-unknown-linux-gnueabi-gcc -pthread -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/xcc/aarch64-unknown-linux-gnueabi/include -I/usr/xcc/aarch64-unknown-linux-gnueabi/include -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -IModules/_multiprocessing -I./Include -I. -I/usr/xcc/aarch64-unknown-linux-gnueabi/include -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/tmp/tmp.JY5YOL4mLZ/cpython-3.7.6/Include -I/tmp/tmp.JY5YOL4mLZ/cpython-3.7.6 -c /tmp/tmp.JY5YOL4mLZ/cpython-3.7.6/Modules/_multiprocessing/multiprocessing.c -o build/temp.linux-aarch64-3.7/tmp/tmp.JY5YOL4mLZ/cpython-3.7.6/Modules/_multiprocessing/multiprocessing.o
In file included from /usr/xcc/aarch64-unknown-linux-gnueabi/aarch64-unknown-linux-gnueabi/sysroot/usr/include/features.h:434:0,
                 from /usr/xcc/aarch64-unknown-linux-gnueabi/aarch64-unknown-linux-gnueabi/sysroot/usr/include/bits/libc-header-start.h:33,
                 from /usr/xcc/aarch64-unknown-linux-gnueabi/aarch64-unknown-linux-gnueabi/sysroot/usr/include/limits.h:26,
                 from /usr/xcc/aarch64-unknown-linux-gnueabi/lib/gcc/aarch64-unknown-linux-gnueabi/4.9.4/include-fixed/limits.h:168,
                 from /usr/xcc/aarch64-unknown-linux-gnueabi/lib/gcc/aarch64-unknown-linux-gnueabi/4.9.4/include-fixed/syslimits.h:7,
                 from /usr/xcc/aarch64-unknown-linux-gnueabi/lib/gcc/aarch64-unknown-linux-gnueabi/4.9.4/include-fixed/limits.h:34,
                 from ./Include/Python.h:11,
                 from /tmp/tmp.JY5YOL4mLZ/cpython-3.7.6/Modules/_multiprocessing/multiprocessing.h:6,
                 from /tmp/tmp.JY5YOL4mLZ/cpython-3.7.6/Modules/_multiprocessing/multiprocessing.c:10:
/usr/include/x86_64-linux-gnu/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>

Also, Python configure script prints "INFO: Could not locate ffi libs and/or headers"

The libffi install script (which runs before python) prints:

 /usr/bin/install -c -m 644 ffi.h ffitarget.h '/usr/xcc/aarch64-unknown-linux-gnueabi/include'

Libraries have been installed in:
   /usr/xcc/aarch64-unknown-linux-gnueabi/lib/../lib64