Fixing AttributeError in "KaldiRecognizer"
AttributeError: 'KaldiRecognizer' object has no attribute '_handle'

self._handle is not pre-defined in "KaldiRecognizer" and if the "if" statements inside "KaldiRecognizer" the last "if" statement , I mean :

if self._handle == _ffi.NULL:
            raise Exception("Failed to create a recognizer")

raises an Attribute Error that no attribute with name _handle is defined .....